<body>
    <div class="panel">
        <div style='font: 13px/1.231 "Segoe UI", Frutiger, "Frutiger Linotype", "Dejavu Sans", "Helvetica Neue", Arial, sans-serif; border: 1px solid #ccc;' >
            <div style="padding: 10px;">
                <h6 style="font-size: 15px;text-align: center;">
                    <?= Util::translate("email.reset_password.title") ?>
                </h6>
                <p><?= Util::translate("email.hello") ?><strong><?php echo $this->fullName; ?></strong>,</p>
                <div>
                    <?= Util::translate("email.reset_password.content1") ?>
                    <br/>
                    <table style='border-collapse: collapse;width: 250px; margin: 20px auto; border:1px solid #ccc;'>
                        <tr style='border:1px solid #ccc;'>
                            <td style='border:1px solid #ccc; padding: 10px 5px; font-size: 12px;text-align: center;'>
                                Username
                            </td>
                            <td style='border:1px solid #ccc; padding: 10px 5px; font-size: 12px; text-align: center; font-weight: bold;'>
                                <?php echo $this->username; ?>
                            </td>
                        </tr>
                        <tr>
                            <td style='border:1px solid #ccc; padding: 10px 5px; font-size: 12px; text-align: center;'>
                                Password
                            </td>
                            <td style='border:1px solid #ccc; padding: 10px 5px; font-size: 12px; text-align: center; font-weight: bold;'>
                                <?php echo $this->password; ?>
                            </td>
                        </tr>
                    </table>
                    <p>
                         <?= Util::translate("email.reset_password.content2") ?>
                    </p>
                </div>

            </div>
            <p style="font-size: 12px; font-style: italic; margin:10px;"><?= Util::translate("email.notification.no_reply") ?> </p>
        </div>
    </div>
</body>