<script>
    $(document).ready(function() {
        tim.initPage({
            jsfiles: [
                {
                    src: "/js/lib/",
                    name: "jquery.autogrow-textarea.js"
                },
                {
                    src: "/js/home/qa/",
                    name: "vm-qa-list.js"
                }
            ],
            messages: {
                titleAlert: '<?= Util::translate("dialog.alert.info.title") ?>',
                successInsertQa: '<?= Util::translate("qa.insert.success") ?>',
                errorInsertQa: '<?= Util::translate("qa.insert.error") ?>'
            },
            bindings: [
                {
                    viewer: "QaListV",
                    viewmodeler: "qaListVM",
                    linkback: true,
                    data: {
                        qas: <?= json_encode($this->qas) ?>,
                        resultCount: '<?= $this->resultCount ?>',
                        keyword: '<?= $this->keyword ?>'
                    }
                }
            ]
        });
    });
</script>

<?php echo $this->render('breadcrumb.phtml'); ?>
<div class="row">
    <div class="main-box" 
         data-viewmodeler="QaListV">
        <div class="nar-12 colunm-left">
            <?php echo $this->render('/news/components/advertising-box.phtml'); ?>
            <div class="f-qa-list b-box"
                 style="margin-bottom: 20px;">
                <div style="background-color:#E46299; height: 5px; margin-bottom: 10px; width: 100%;"></div>
                <h2 class="f-news-title" style="font-size: 14px; text-align: center;">CÂU HỎI CỦA BẠN</h2>
                <div class="f-qa-post">
                    <form data-call="submit: addQa()"
                          id="form-add-qa">
                        <div class="row">
                            <div class="nar-12 pad-12 med-12 wid-12">
                                <span data-message-for="title" 
                                      class="fgr--error"></span>
                                <input type="text" name="title" id="title"
                                       data-check="title: required"
                                       data-required-message="<?= Util::translate("entry.title.error.required") ?>"
                                       placeholder="Tiêu đề (*)"/>
                            </div>
                        </div>
                        <div class="row">
                            <span data-message-for="description" 
                                  class="fgr--error"></span>
                            <textarea id="qa_post" id="description"
                                      name="description"
                                      data-check="description: required"
                                      data-required-message="<?= Util::translate("qa.question_detail.error.required") ?>"
                                      placeholder="Nội dung câu hỏi (*)"></textarea>
                        </div>
                        <div class="row">
                            <div class="nar-12 pad-6 med-6 wid-6">
                                <span data-message-for="asker" 
                                      class="fgr--error"></span>
                            </div>
                            <div class="nar-12 pad-6 med-6 wid-6">
                                <span style="margin-left: 5px;display: block;"
                                      data-message-for="askerEmail" 
                                      class="fgr--error"></span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="nar-12 pad-6 med-6 wid-6"
                                 style="padding-right: 5px;height: auto;">
                                <input type="text" id="asker"
                                       name="asker"
                                       data-check="asker: required"
                                       data-required-message="<?= Util::translate("qa.asker.error.required") ?>"
                                       placeholder="Tên của bạn (*)"/>
                            </div>
                            <div class="nar-12 pad-6 med-6 wid-6"
                                 style="padding-left: 5px;height: auto;">
                                <input type="text" 
                                       name="askerEmail" 
                                       id="askerEmail"
                                       data-check="askerEmail: isemail"
                                       data-isemail-message="Email không hợp lệ"
                                       placeholder="Email của bạn"/>
                            </div>
                        </div>
                        <div class="row">
                            <img src="/img/icon/loading.gif" style="width: 20px; display: none;"
                                 id="img-loading-insert"/>
                            <button class="button button--sm f-button">Hỏi</button>
                            <button class="button button--sm f-button" type="reset">Làm lại</button>
                        </div>
                    </form>
                </div>
                <?php
                if (isset($this->keyword)) {
                    ?>
                    <div class="box-header"
                         style="margin-bottom: 15px;">
                        <img src="/img/icon/arrow_header.png"/>
                        <a href='/search?<?= $actionName ?>'>
                            KẾT QUẢ TÌM KIẾM
                        </a>
                    </div>
                    <h4 class="f-search-keyword">
                        Tìm kiếm với từ khóa:<span style='color:#DF3D82' data-out="keyword"></span>
                        <span class="f-search-result">Tìm thấy: <strong style='color:#DF3D82' 
                                                                        data-out="resultCount"></strong> kết quả</span>
                    </h4>
                    <div class='divider--hr'></div>
                    <?php
                } else {
                    ?>
                    <h2 class="f-news-title" style="font-size: 14px;">CÂU HỎI THƯỜNG GẶP</h2>
                    <?php
                }
                ?>
                <?php echo $this->render('/qa/components/qa-item.phtml'); ?>

                <div class="f-paging">
                    <?php echo $this->paginationControl($this->paginator); ?>
                </div>
            </div>
        </div>
        <div class="nar-12 colunm-right">
            <?php echo $this->render('/home/components/supports-box.phtml'); ?>
            <?php echo $this->render('/home/components/network-box.phtml'); ?>
            <?php echo $this->render('/home/components/subcrible-box.phtml'); ?>
             <?php echo $this->render('menu-right.phtml'); ?>
            <?php echo $this->render('/home/components/advertising-box.phtml'); ?>
            <?php echo $this->render('/home/components/video-box.phtml'); ?>
        </div>
    </div>
</div>

<?php echo $this->render("components/dialog-confirm.phtml"); ?>