<style>
    .dialog-popup{
        position: absolute;
        z-index: 1002;
        background-color: #fff;
        overflow: hidden;
        height: 125px;
        min-width: 200px;
        display: none;
        border: 1px solid #ddd;
    }

    .popup-items{
        padding: 10px 0;
        position: relative;
        overflow: hidden;
    }

    .popup-item{
        width: 100%;
        height: 26px;
        position: relative;
        padding-top: 3px;
    }

    /*    .popup-table{
            display: table;
        }
        
        .popup-table .popup-item{
            display: table-row;
        }
    
        .popup-table .item-key, 
        .popup-table .item-value{
            display: table-cell;
            width: auto;
        }
    
        .popup-block{
            display: inline-block;
            overflow: hidden;
        }
    
        .popup-block .item-key, 
        .popup-block .item-value{
            float: left;
            width: 100%;
        }*/

    .popup-item .item-key, 
    .popup-item .item-value{
        display: inline-block;
        font-size: 12px;
        color: #555;
        padding:0 10px;
        line-height: 24px;
    }
    
    .popup-item:hover{
        background-color: #eee;
        color: #111;
        cursor: pointer;
    }

    .popup-item--active{
        background-color: #eee;
        color: #111;
    }

    .popup-loading{
        position: absolute;
        right: 5px;
        top:5px;
        display: none;
    }

    .popup-loading img{
        width: 25px;
        height: 25px;
    }
    .popup-not-found{
        font-size: 12px;
        color: #666;
        display:none;
        text-align: center;
        width: 100%;
        margin-top: 10px;
    }
</style>
<div id="dialog_popup"
     class="dialog-popup">
    <div class="popup-loading">
        <img src="/img/icon/loading.gif"/>
    </div>
    <p class="popup-not-found"><?= Util::translate("message.search.notfound") ?></p>
    <div class="popup-items"
         data-control="for: item in mapItems">
        <div class="popup-item"
             data-attr="data-index: item.$index">
            <span class="item-key"
                  data-item="item.key"></span>
            <span class="item-value"
                  data-item="item.value"></span>
        </div>
    </div>
</div>
