<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<?php
$request = Zend_Controller_Front::getInstance()->getRequest();
$moduleName = $request->getModuleName();
$controllerName = $request->getControllerName();
$actionName = $request->getActionName();
$keywords = Services::createConfigurationService()->get("home.meta.keywords");
$description = Services::createConfigurationService()->get("home.meta.description");
$livechat = Services::createConfigurationService()->get("home.livechat");
$googleanalytic = Services::createConfigurationService()->get("home.googleanalytic");
$facebookcode = Services::createConfigurationService()->get("home.facebookcode");
$facebookAppId = Services::createConfigurationService()->get("facebook.application.id");
$facebookAdminsId = Services::createConfigurationService()->get("facebook.admins.id");
$entry = isset($this->entry) ? $this->entry : NULL;
$category = isset($this->category) ? $this->category : NULL;
$actual_link = "http://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";
?>

<html xmlns="http://www.w3.org/1999/xhtml">
    <head>        
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <meta name="revisit-after" content="1 days"/>
        <meta property="fb:app_id" content="<?= $facebookAppId!=null?$facebookAppId->getValue():''?>"/>
        <meta property="fb:admins" content="<?= $facebookAdminsId!=null?$facebookAdminsId->getValue():''?>"/> 
        <script type="text/javascript" src="/js/jquery/jquery-1.10.1.min.js"></script>
        <script type="text/javascript" src="/js/lib/jquery-ui-1.10.4.custom.min.js"></script>
<!--        <script type="text/javascript" src="http://www.skypeassets.com/i/scom/js/skype-uri.js"></script>-->
        <!--timjs-->
        <script type="text/javascript" src="/js/timjs/timjs-1.3.4.1.js"></script>

        <link href="/css/system/smoothness/jquery-ui-1.10.4.custom.css" rel="stylesheet"></link>

        <!--timstyle-->
        <link href="/css/timstyle/normalize.css" rel="stylesheet"></link>
        <link href="/css/timstyle/timstyle.core-1.3.css" rel="stylesheet"></link>
        <link href="/css/timstyle/timstyle.theme-1.3.css" rel="stylesheet"></link>
        <link href="/css/timstyle/slideshow-theme.css" rel="stylesheet" ></link>
        <link href="/css/timstyle/slideshow.css" rel="stylesheet" ></link>
        <script type="text/javascript" src="/css/timstyle/timstyle-1.3.js"></script>  
        <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">

<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
<link rel="icon" href="/favicon.ico" type="image/x-icon">      

        <link href="/css/home/benhkhotho-home.css" rel="stylesheet"></link>
        <meta Name="Abstract" Content="Hồ sơ du học pháp"/>
        <meta name="Author" Content="Việt Pháp Á Âu"/>
        <meta name="copyright" content="Copyright 2015"/>
        <meta Name="msnbot" Content="NOODP"/>
        <meta http-equiv="Content-Script-Type" Content="text/javascript"/>
        <meta http-equiv="expires" Content="Wed, 26 Feb 2015 08:21:57 GMT"/>
        <meta name="generator" content="Vietphataau" />
        <meta http-equiv="Pragma" Content="no-cache" />
        <meta name="robots" content="index, follow" />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="<?= $actual_link ?>" />
        <?php if (($controllerName == "qa" ) && ($actionName == "view") && $qa != NULL) { ?>
            <meta property="og:title" content="<?= $qa['title'] ?>" />
            <meta property="og:description" content="<?= strip_tags($qa['description']) ?>"/>
            <meta property="og:image" content="<?= "http://" . $_SERVER[HTTP_HOST] . "/img/banner/logo.jpg" ?>" />
        <?php } else if (($controllerName == "news" ) && ($actionName == "view-article") && $entry != NULL) { ?>
            <meta property="og:image" content="<?= "http://" . $_SERVER[HTTP_HOST] . $entry['imagePath'] ?>" />
            <meta property="og:title" content="<?= $entry['title'] ?>" />
            <meta property="og:description" content="<?= strip_tags($entry['description']) ?>"/>

        <?php } else {
            ?>
            <meta property="og:image" content="<?= "http://" . $_SERVER[HTTP_HOST] . "/img/banner/logo.jpg" ?>"  />
            <meta property="og:title" content="Hồ sơ du học Pháp" />
            <meta property="og:description" content="<?= $description->getValue() ? $description->getValue() : '' ?>"/>
            <?php
        }
        ?>
        <?php if ($entry == NULL && $category == NULL) { ?>    
            <meta name="description" content="<?= $description->getValue() ? $description->getValue() : '' ?>"/>
            <meta name="keywords" content="<?= $keywords->getValue() ? $keywords->getValue() : '' ?>"/> 
        <?php } else if ($entry == NULL && $category != NULL) { ?> 
            <meta name="description" content="<?= $category["seoDescription"] ?>"/>
            <meta name="keywords" content="<?= $category["seoKeyword"] ?>"/> 
            <meta name="Subject" Content="<?= $category["name"] ?>" />
        <?php } else {
            ?>
            <meta name="description" content="<?= $entry["seoDescription"] ?>"/>
            <meta name="keywords" content="<?= $entry["seoKeyword"] ?>"/> 
            <meta name="Subject" Content="<?= $entry["seoTitle"] ?>" />
        <?php }
        ?>
        <script type="text/javascript" src="/js/home/benhkhotho-home.js"></script>

       
        <?php
        if ($livechat != null) {
            echo $livechat->getValue();
        }
        ?>
        <?php
        if ($googleanalytic != null) {
            echo $googleanalytic->getValue();
        }
        ?>

        <?php
        if (isset($this->navigations)) {
            $title = end($this->navigations);
            if ($title["name"] != null) {
                echo "<title>" . $title["name"] . "</title>";
            }
        } else {
            echo "<title>" . ($keywords->getValue() ? $keywords->getValue() : '') . "</title>";
        }
        ?>

    </head>
    <body>
        <div id="fb-root"></div>
         <?php
        if ($facebookcode != null) {
            echo $facebookcode->getValue();
        }
        ?>
        <?php
        if (isset($this->navigations)) {
            $title = end($this->navigations);
            if ($title["name"] != null) {
                echo "<h1 style='display:none;'>" . $title["name"] . "</h1>";
            }
        } else {
            echo "<h1 style='display:none;'>" . ($keywords->getValue() ? $keywords->getValue() : '') . "</h1>";
        }
        ?>
        <?php echo $this->render('home/header.phtml'); ?>
        <?php echo $this->layout()->content; ?>
        <?php echo $this->render('home/footer.phtml'); ?>
        <?php echo $this->render('home/menu-extra.phtml'); ?>
        <a class="scroll-up visible-nar"
           href="#anchorTop">
            <img src="/img/icon/up_arrow.png" /> 
        </a>
    </body>
</html>
