<?php
$request = Zend_Controller_Front::getInstance()->getRequest();
$status = isset($this->flag) ? $this->flag : $request->getParam("flag");
?>
<style>
    ul{
        list-style: none;
    }
</style>
<script>
    $(document).ready(function() {
        tim.initPage({
            jsfiles: [
                {
                    src: "/js/system/user/",
                    name: "vm-user-change-password.js"
                }
            ],
            bindings: [
                {
                    viewer: "UserChangePasswordV",
                    viewmodeler: "userChangePassWordVM",
                    linkback: true,
                    data: {
                        user: <?= json_encode($this->user) ?>
                    }
                }
            ]
        });
    });
</script>
<div class="panel content"
     style="text-align: center;">
    <div data-viewmodeler="UserChangePasswordV"
         style="width: 100%; height: 300px; text-align: center;">
        <div id="alert_success"
             class="alert--success rounded--sm"
             style="<?= isset($status) && $status == "success" ? 'display: block;' : 'display: none;' ?>">
            <span class="alert-content">
                <?= Util::translate("message.changepassword.success") ?> 
            </span>
            <span class="alert-close" 
                  onclick="$(this).parent().hide();">&times;</span>
        </div>
        <div id="alert_error"
             class="alert--error rounded--sm"
             style="<?= isset($status) && $status == "error" ? 'display: block;' : 'display: none;' ?>">
            <span class="alert-content">
                <?= Util::translate("message.changepassword.error") ?> 
            </span>
            <span class="alert-close" 
                  onclick="$(this).parent().hide();">&times;</span>
        </div> 
        <form data-call="submit: updateValueForm"
              method="POST" 
              action="/system/user/change-password">
            <div class="dogo-body"
                 style="margin: 0 auto; height: 300px; position: relative;">
                <div style="width: 450px; margin: 10px auto;">
                    <h6 class="sys-title center-text">
                        <?= Util::translate("user.list.cnu.title") ?> 
                    </h6>
                    <div class="row border--thin rounded--sm"
                         style="margin: 15px; padding-right: 15px;">
                        <table class="table--info" style="width: 100%;">
                            <tr>
                                <td style="width: 160px;">
                                    <?= Util::translate("person.password") ?>
                                </td>
                                <td>
                                    <?php if (isset($this->message)) {
                                        ?>
                                        <span id="currentPassword"
                                            class="fgr--error">
                                            <?php echo $this->message; ?>
                                        </span>
                                        <?php
                                    }
                                    ?>
                                    <span data-message-for="password" 
                                          class="fgr--error"></span>
                                    <input name="password" 
                                           type="password"
                                           data-check="password: required"
                                           data-required-message="<?= Util::translate("message.input.required", array("name" => Util::translate("person.password"))) ?>"/>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <?= Util::translate("person.new_password") ?>
                                </td>
                                <td>
                                    <span data-message-for="newPassword" 
                                          class="fgr--error"></span>
                                    <input name="newPassword" 
                                           type="password"
                                           data-check="newPassword: required"
                                           data-required-message="<?= Util::translate("message.input.required", array("name" => Util::translate("person.new_password"))) ?>"/>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <?= Util::translate("person.renew_password") ?>
                                </td>
                                <td>
                                    <span id="confirmPassword" 
                                          class="fgr--error"
                                          style="display: none;">
                                              <?= Util::translate("message.password.confirm") ?>  
                                    </span>
                                    <input name="confirmPassword" 
                                           type="password" />
                                </td>
                            </tr>
                        </table>
                        <div class="table-footer"
                             style="text-align: right; padding: 5px 10px 15px 0">
                            <button type="reset" class="button--sm" 
                                    style="margin-right: 5px;">
                                        <?= Util::translate("form.button.reset") ?>
                            </button>
                            <button type="submit" class="button--sm">
                                <?= Util::translate("form.button.save") ?>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
