<?php
$request = Zend_Controller_Front::getInstance()->getRequest();
$authen = $request->getParam("authentication");
?>
<script>
    $(document).ready(function() {
        tim.initPage({
            jsfiles: [
                {
                    src: "/js/home/customer/",
                    name: "vm-new-password.js"
                }
            ],
            bindings: [
                {
                    viewer: "signupV",
                    viewmodeler: "signupVM",
                    linkback: true,
                    data: {
                        existUser: '<?= $this->existUser ?>',
                        authentication: '<?= $authen ?>',
                        success: '<?= $this->success ?>'
                    }
                }
            ]
        });
    });
</script>
<div class="panel">
    <div data-viewmodeler="signupV">
        <div class="row">
            <div class="topsale-panel"
                 style="padding-top: 50px; margin-top: 0;">
                <div class="container">
                    <div class="row">
                        <div class="table table--none rounded--md" 
                             style="padding: 15px; width: 550px; margin: 0 auto;
                             background-color: #fff; padding: 20px; overflow: hidden;">
                            <p id="success_alert"
                               style="display: none;">Khôi phục mật khẩu thành công.</p>
                            <form id="loginform" method="POST" 
                                  action="/home/user/new-password?resetkey=<?= isset($this->resetkey) ? $this->resetkey : "" ?>"
                                  data-call="submit: updateValueForm">
                                <div class="timgether-signup">
                                    <div class="signup-box">
                                        <h6 class="fgr-purple"
                                            style="padding-bottom:8px;text-align: center;font-size: 150%;">Khôi phục mật khẩu</h6>
                                        <span data-message-for="password" 
                                              class="fgr--error login-error"></span>
                                        <span  style="font-size: 12px;margin: 3px;">Mật khẩu</span>    
                                        <input id="input-password"
                                               style="margin-top: 3px; margin-bottom: 10px;"
                                               name="password"
                                               type="password" 
                                               placeholder="Mật khẩu"
                                               data-check="password: required"
                                               data-required-message="Yêu cầu nhập mật khẩu"/>
                                        <span  style="font-size: 12px;margin: 3px;">Nhập lại mật khẩu</span>    
                                        <input id="input2-password"
                                               style="margin-top: 3px; margin-bottom: 10px;"
                                               name="password2"
                                               type="password" 
                                               placeholder="Nhập lại mật khẩu"
                                               data-check="password: required"
                                               data-required-message="Yêu cầu nhập lại mật khẩu"/>
                                        <span data-message-for="password2" 
                                              class="fgr--error login-error" id="span-error-password2"></span>
                                        <button type="submit" 
                                                class="button button--sm float--right rounded--sm"
                                                style="margin-top: 25px;">
                                            Lưu
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

