<?php
$request = Zend_Controller_Front::getInstance()->getRequest();
$authen = $request->getParam("authentication");
?>
<script>
    $(document).ready(function() {
        tim.initPage({
            jsfiles: [
                {
                    src: "/js/home/customer/",
                    name: "vm-reset-password.js"
                }
            ],
            bindings: [
                {
                    viewer: "resetpasswordV",
                    viewmodeler: "resetpasswordVM",
                    linkback: true,
                    data: {
                        success: '<?= $this->success ?>'
                    }
                }
            ]
        });
    });
</script>
<div class="panel">
    <div data-viewmodeler="resetpasswordV">
        <div class="row">
            <div class="topsale-panel"
                 style="padding-top: 50px; margin-top: 0;">
                <div class="container">
                    <div class="row">
                        <div class="table table--none rounded--md" 
                             style="padding: 15px; width: 550px; margin: 0 auto;
                             background-color: #fff; padding: 20px;">
                            <div id="success-message" style="text-align: center; margin: 40px auto; color: #666; font-size: 13px;">Hướng dẫn thay đổi mật khẩu đã được gửi vào email của bạn. Vui lòng kiểm tra email để lấy lại mật khẩu</div>
                            <form id="loginform" method="POST" 
                                  action="/home/user/reset-password"
                                  data-call="submit:">
                                <div style="padding: 15px 30px;">
                                    <h6 class="fgr-purple"
                                        style="padding-bottom:8px;text-align: center;font-size: 150%;">Yêu cầu tạo lại mật khẩu</h6>
                                    <label style="font-size: 12px;">Địa chỉ email đã đăng ký</label>
                                    <input name ="email" 
                                           id="input-email"
                                           type="text" 
                                           placeholder="Email" 
                                           data-check="email: required,isemail"
                                           data-isemail-message="Email không đúng đinh dạng!"
                                           data-required-message="Yêu cầu nhập email!"/>
                                    <button type="submit" 
                                            class="button button--sm float--right rounded--sm"
                                            style="margin-top: 10px; width: 60px;">
                                        Gửi
                                    </button>
                                    <p style="text-align: center; margin: 40px auto; color: #666; font-size: 13px; padding-top: 30px;">Bằng việc gửi địa chỉ email bạn đã đăng ký. Chúng tôi sẽ gửi lại mật khẩu mới qua email này trong một vài phút.</p>
                                </div>
                            </form>

                        </div>
                    </div>  
                </div>

            </div>
        </div>
    </div>
</div>
