<script src="https://apis.google.com/js/platform.js" async defer>
</script>
<script>
    $(document).ready(function() {
        tim.initPage({
            jsfiles: [
                {
                    src: "/js/home/news/",
                    name: "vm-entry-view.js"
                }
            ],
            bindings: [
                {
                    viewer: "EntryV",
                    viewmodeler: "entryVM",
                    linkback: true,
                    data: {
                        entry:<?= json_encode($this->entry); ?>,
                        suggestionEntries:<?= json_encode($this->suggestionEntries) ?>,
                        innerRightMenus: <?= json_encode($this->menuInnerRight) ?>,
                        categoryName: '<?= $this->categoryName ?>'
                    }
                }
            ]
        });
    });
</script>

<?php echo $this->render('breadcrumb.phtml'); ?>
<div class="row">
    <div class="main-box" 
         data-viewmodeler="EntryV">
        <div class="row">
            <div class="nar-12 colunm-left">
                <div style="padding-right:30px;">
                    <?php echo $this->render('/news/components/advertising-box.phtml'); ?>
                </div>
                <div class="f-news-detail"
                     style="margin-top: 10px;">
                    <div style="background-color:#E46299; height: 5px; margin-bottom: 10px; width: 100%;"></div>
                    <h4 class="f-news-title" style="font-weight: bold;font-size: 120%"  data-out="entry.title"></h4>
                    <div class="news-time fgr-text"
                         style="margin: 0;">
<!--                        <img src="/img/icon/clock_23.png"/>-->
<!--                        <span data-out="entry.createTime"></span>-->
                        <div class="f-like"
                             style="margin-top: 0px;">
                            <div class="fb-like"
                                 style="margin-left: 10px;"
                                 data-attr="data-href:document.URL" 
                                 data-layout="button_count" 
                                 data-action="like" 
                                 data-show-faces="false" 
                                 data-share="false"></div>
                            <div style="margin: 0 0 0 10px; display: inline-block;  width: 77px !important; overflow: hidden;">
                                <a class="twitter-share-button" 
                                   href="https://twitter.com/share"
                                   data-related="twitterdev"
                                   data-size="medium"
                                   data-count="horizontal">
                                    Tweet
                                </a>
                            </div>
                            <div style="margin: 0 0 0 10px; display: inline-block; width: 77px !important; overflow: hidden;">
                                <div class="g-plusone"
                                     data-size="medium"
                                     style="margin-left: 10px;"></div>
                            </div>
                        </div>
                    </div>
                    <div class="row"
                         data-control="if: entry.asker">
                        <span style="font-size: 13px; padding-bottom: 10px;"> 
                            Người hỏi: <strong style="color:#0076BC"
                                               data-out="entry.asker"></strong>
                        </span>
                    </div>
                    <div class="divider--hr"></div>
                    <div class="row"
                         data-control="if: entry.asker">
                        <span class="f-qa-subtitle">Chi tiết câu hỏi:</span>
                        <h2 class="f-short-description"  
                            data-out="entry.description" 
                            data-type="html">
                        </h2>
                        <span class="f-qa-subtitle">Trả lời:</span>
                    </div>
                     <div class="f-news-description"  
                         data-out="entry.description"
                         data-type="html">
                    </div>
                    <div class="f-news-content"  
                         data-out="entry.content"
                         data-type="html">
                    </div>
                    <div class="f-sharing">
                        <a class="f-link-item" 
                           data-attr="href:document.URL" 
                           target="_blank" 
                           onclick="window.open('https://www.facebook.com/sharer/sharer.php?u=' + encodeURIComponent(document.URL) + '&t=' + encodeURIComponent(document.URL));
                                   return false;">
                            <img src="/img/icon/facebook.png"/>
                        </a>
                        <a class="f-link-item" 
                           data-attr="href:document.URL" 
                           target="_blank" title="Share on Google+" 
                           onclick="window.open('https://plus.google.com/share?url=' + encodeURIComponent(document.URL));
                                   return false;">
                            <img src="/img/icon/googleplus.png"/>
                        </a>
                        <a class="f-link-item" 
                           data-attr="href:document.URL" 
                           target="_blank" title="Tweet" 
                           onclick="window.open('https://twitter.com/intent/tweet?text=' + encodeURIComponent(document.title) + ':%20' + encodeURIComponent(document.URL));
                                   return false;">
                            <img src="/img/icon/twitter.png"/>
                        </a>
                        <div class="f-like">
                            <div class="fb-like"
                                 style="margin-left: 10px;"
                                 data-attr="data-href:document.URL" 
                                 data-layout="button_count" 
                                 data-action="like" 
                                 data-show-faces="false" 
                                 data-share="false"></div>
                            <div style="margin: 3px 0 0 10px; display: inline-block;  width: 77px !important; overflow: hidden;">
                                <a class="twitter-share-button" 
                                   href="https://twitter.com/share"
                                   data-related="twitterdev"
                                   data-size="medium"
                                   data-count="horizontal">
                                    Tweet
                                </a>
                            </div>
                            <div style="margin: 3px 0 0 10px; display: inline-block; width: 77px !important; overflow: hidden;">
                                <div class="g-plusone"
                                     data-size="medium"
                                     style="margin-left: 10px;"></div>
                            </div>
                        </div>
                    </div>
                    <div class="news-tags border--thin rounded--md" style="margin-bottom: 5px">
                        <span class="bold"
                              style="float:left;color: #E3860D">Tags:</span>
                        <ul class="menu-hr"
                            style="width:auto; float: left;"
                            data-control='for: tag in tags'>
                            <li class="menu-item"
                                style="width: auto;">
                                <a data-attr="href:'/search?keyword=' + tag.name"
                                   data-item='tag.name'></a>
                            </li>
                        </ul>
                    </div>
                    <div  class="fb-comments" 
                          data-width="100%"
                          data-attr='data-href: document.URL' 
                          data-numposts="5" 
                          data-colorscheme="light"
                          data-version="v2.3"></div>
                </div>
                <?php
                if (isset($this->suggestionEntries) && count($this->suggestionEntries) > 0) {
                    ?>
                    <div class="row"
                         style="margin-top: 10px;">
                        <div class="f-news-detail">
                            <h4 class="f-news-title"
                                style="font-size:120%;">BÀI VIẾT CÙNG CHUYÊN MỤC</h4>
                            <div class="f-news-relative">
                                <?php echo $this->render('/news/components/entry-relative-item.phtml'); ?>
                            </div>
                        </div>
                    </div>
                    <?php
                }
                ?>
            </div>
            <div class="nar-12 colunm-right">
                <?php echo $this->render('/home/components/supports-box.phtml'); ?>
                <?php echo $this->render('/home/components/network-box.phtml'); ?>
                <?php echo $this->render('menu-right.phtml'); ?>
                <?php echo $this->render('/home/components/advertising-box.phtml'); ?>
                <?php echo $this->render('/home/components/video-box.phtml'); ?>
            </div>
        </div>

    </div>
</div>

<script>
    window.twttr = (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0], t = window.twttr || {};
        if (d.getElementById(id))
            return;
        js = d.createElement(s);
        js.id = id;
        js.src = "https://platform.twitter.com/widgets.js";
        fjs.parentNode.insertBefore(js, fjs);
        t._e = [];
        t.ready = function(f) {
            t._e.push(f);
        };
        return t;
    }(document, "script", "twitter-wjs"));
</script>