<script>
    $(document).ready(function() {
        tim.initPage({
            jsfiles: [
                {
                    src: "/js/home/news/",
                    name: "vm-one-category-list.js"
                }
            ],
            bindings: [
                {
                    viewer: "OneCategoryListV",
                    viewmodeler: "oneCategoryListVM",
                    linkback: true,
                    data: {
                        entries:<?= json_encode($this->entries); ?>,
                        categoryType: '<?= json_encode($this->categoryType); ?>',
                        categoryId: '<?= json_encode($this->categoryId); ?>',
                        category: <?= json_encode($this->category); ?>
                    }
                }
            ]
        });
    });
</script>

<?php echo $this->render('breadcrumb.phtml'); ?>
<div class="row">
    <div class="main-box" 
         data-viewmodeler="OneCategoryListV">
        <div class="nar-12 colunm-left">
          
            <div class="box-category" style="padding-bottom: 25px;">
                <div class="box-header"
                     style="margin-bottom: 15px;">
                    <img src="/img/icon/arrow_header.png"/>
                    <a data-attr="href:'/'+ oneCategoryListVM.category.rewriteUrl"
                       data-out="oneCategoryListVM.category.name"> 
                    </a>
                </div>
                <div class="row"
                     data-control="for: entry in entries">
                         <?php echo $this->render('/news/components/news-of-category-item.phtml'); ?>
                </div>
                <div class="f-paging"
                     style="padding-right: 10px;">
                         <?php echo $this->paginationControl($this->paginator); ?>
                </div>
            </div>
        </div>
        <div class="nar-12 colunm-right">
            <?php echo $this->render('/home/components/supports-box.phtml'); ?>
            <?php echo $this->render('/home/components/network-box.phtml'); ?>
            <?php echo $this->render('/home/components/subcrible-box.phtml'); ?>
            <?php echo $this->render('menu-right.phtml'); ?>
            <?php echo $this->render('/home/components/advertising-box.phtml'); ?>
            <?php echo $this->render('/home/components/video-box.phtml'); ?>
        </div>
    </div>
</div>
