<?php
$request = Zend_Controller_Front::getInstance()->getRequest();
$controllerName = $request->getControllerName();
$actionName = $request->getActionName();
?>
<script>
    $(document).ready(function() {
        tim.initPage({
            jsfiles: [
                {
                    src: "/js/home/news/",
                    name: "vm-search-list.js"
                }
            ],
            bindings: [
                {
                    viewer: "SearchListV",
                    viewmodeler: "searchListVM",
                    linkback: true,
                    data: {
                        entries:<?= json_encode($this->entries); ?>,
                        keyword: '<?= $this->keyword ?>',
                        resultCount: '<?= $this->resultCount ?>',
                    }
                }
            ]
        });
    });
</script>
<div class="row"
     style="margin-top: 20px;">
    <div class="main-box" 
         data-viewmodeler="SearchListV">
        <div class="nar-12 colunm-left">
            <div class="box-category" style="padding-bottom: 25px;">
                <div class="box-header"
                     style="margin-bottom: 15px;">
                    <img src="/img/icon/arrow_header.png"/>
                    <a href='/search?<?= $actionName ?>'>
                        KẾT QUẢ TÌM KIẾM
                    </a>
                </div>
                <h4 class="f-search-keyword">
                    Tìm kiếm với từ khóa:<span style='color:#DF3D82' data-out="keyword"></span>
                    <span class="f-search-result">Tìm thấy: <strong style='color:#DF3D82' data-out="resultCount"></strong> kết quả</span>
                </h4>
                <div class='divider--hr'></div>
                <div class="row"
                     data-control="for: entry in entries">
                         <?php echo $this->render('/news/components/news-of-category-item.phtml'); ?>
                </div>
                <div class="f-paging"
                     style="padding-right: 10px;">
                         <?php echo $this->paginationControl($this->paginator); ?>
                </div>
            </div>
        </div>
        <div class="nar-12 colunm-right">
            <?php echo $this->render('/home/components/supports-box.phtml'); ?>
            <?php echo $this->render('/home/components/network-box.phtml'); ?>
            <?php echo $this->render('/home/components/subcrible-box.phtml'); ?>
            <?php echo $this->render('menu-right.phtml'); ?>
            <?php echo $this->render('/home/components/advertising-box.phtml'); ?>
            <?php echo $this->render('/home/components/video-box.phtml'); ?>
        </div>
    </div>
</div>
