<body>
    <div class="panel">
        <div style='font: 13px/1.231 "Segoe UI", Frutiger, "Frutiger Linotype", "Dejavu Sans", "Helvetica Neue", Arial, sans-serif; border: 1px solid #ccc;' >
            <div style="width: 100%; height: 60px; background-color: #009900;">
                <div style="color: #fff; float: left; margin: 20px; font-weight: bold;">
                    VNBUYERS.COM
                </div>
                <div style="float: right;margin: 30px;color: #fff;">
                    <?= Util::translate("email.company.slogan") ?>
                </div>
            </div>
             <!--paragraph component-->
                        <p> Xin chào bạn  </p>

                        <div style="font-size: 14px;">
                            Chúng tôi nhận được yêu cầu khôi phục mật khẩu của bạn vào lúc <?= $this->timereset; ?>.

                        </div>
                        <div style="font-size: 14px;">
                            Nếu không muốn khôi phục mật khẩu, hãy bỏ qua email này.
                        </div>

                        <div style="font-size: 14px;">
                            Bãn hãy nhấn vào đường link sau để nhập mật khẩu: </br>
                        </div>
                        <p style="text-align: center; margin-top: 10px" >
                            <a style="color: #fff; text-decoration: none; font-size: 14px; background-color: #CC054B; padding: 8px 35px;" 
                               href="http://localhost/home/user/new-password?resetkey=<?= $this->keyreset; ?>"> Nhập mật khẩu mới </a>
                        <p>

                        <p>Đường link này có thời hạn là một ngày kể từ khi có yêu cầu đổi mật khẩu</p>
            <div style="background-color: #D7C4E2; height: 80px; padding: 10px;">
                <table>
                    <tr>
                        <td>
                            <!--                            http://localhost/img/icon/logo.jpg-->
                            <div style="background-image: url('<?php echo $this->logoUrl; ?>'); background-size: 80px 80px; height: 80px; width: 80px;background-repeat: no-repeat;"></div>
                        </td>
                        <td style="text-align: left; vertical-align: top;">
                            <ul style="list-style: none; font-size: 12px; margin: 0;">
                                <li style='margin-bottom: 5px;'>
                                    <?= Services::createConfigurationService()->get('footer.company.name')->getValue() ?>
                                </li>
                                <li style='margin-bottom: 5px;'>
                                    <?= Util::translate("email.company.address") ?><?= Services::createConfigurationService()->get('footer.company.address')->getValue() ?>
                                </li>
                                <li style='margin-bottom: 5px;'>
                                    <?= Util::translate("email.company.phone") ?><?= Services::createConfigurationService()->get('footer.company.hotline')->getValue() ?>
                                </li>
                            </ul>
                        </td>
                    </tr>
                </table>
            </div>
            <p style="font-size: 12px; font-style: italic; margin:10px;"><?= Util::translate("email.notification.no_reply") ?> </p>
        </div>
    </div>
</body>