<div class="nar-12 pad-6 med-6 wid-6">
    <a data-attr="href: '/'+change_alias(entry.title) +'-'+ entry.id+'.html'"
       class="f-news-item" style="height: 310px">
        <div class="f-news-header">
            <h4 data-out="strimStringOfDom(entry.title,40)"></h4>
            <span class="f-next-news-icon"></span>
        </div>
        <div data-out="entry.description" data-type='html'></div>
    </a> 