<div class="f-box-supporter">
    <a href="#">
        <h4>Chuyên gia tư vấn</h4>
        <img src=" <?php echo $this->expert_img; ?>"/>
        <span class="f-supporter-position"><?php echo $this->expert_position; ?></span>
        <span class="f-supporter-name"><?php echo $this->expert_name; ?></span>
        <span class="f-supporter-description">
            <?php echo $this->expert_des; ?>
        </span>
        <a class="button button-question" href="/hoi-dap">
            GỬI CÂU HỎI TẠI ĐÂY
        </a>
    </a>
</div>