<div class="border--thin"
     style="margin-top: 5px; margin-right: 10px;">
    <div data-viewmodeler="CatalogSlideV">
        <h6 class="event-header">
            <a href="/thu-vien/">Thư viện Ảnh »</a>
        </h6>
        <div class="slides slides-banner"
             id="catalog_slide" 
             data-control="for: image in catalogImages">
            <div class="slide">
                <div class="slide-image">
                    <img class="slide-img" 
                         data-attr="src: image.thumbnailUrl" />
                </div>
            </div>
        </div>
    </div>
</div>