<?php
$map = Services::createConfigurationService()->get("home.mapurl");
if ($map != NULL) {
    ?>
    <div class="border--thin"
         style="margin-top: 5px; margin-right: 10px;">    
        <h6 class="event-header">
            <p style="font-size: 90%;padding-top: 8px;height: 100%;display: inline-block;">Liên hệ</p>
        </h6>
        <div class="contact-item">
            <iframe width="298" height="250" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" 
                    src="<?= $map->getValue() ?>" >
            </iframe>
        </div>
    </div>
<?php } ?>