<?php
header('X-Frame-Options: GOFORIT');
$social = Services::createConfigurationService()->get("facebook.fanpage.box");
if ($social != NULL) {
    ?>
    <div class="row">
        <div class="f-menu-right-item">
            <div class="f-menu-header">
                <h4 class="visible-pad visible-med visible-wid">LIÊN HỆ & MẠNG XÃ HỘI</h4>
                <h4 class="visible-nar">LIÊN HỆ</h4>
            </div>
            <div class="f-menu-right-content"
                 style="padding: 0;">
                <div class="f-menu-right-category"
                     style="padding: 10px 0;overflow: hidden;">
                    <div class="f-menu-item"
                         style="float: left; margin: 6px 15px;">
                        <img src="/img/icon/phone_red_26_26.png"
                             alt="Số điện thoại nóng"/>
                        <span style="color: #FE5757; font-size: 14px; font-weight: bold;"
                              data-out="'Hotline: ' + headerVM.hotline">
                        </span>
                    </div>
                    <div class="f-menu-item"
                         style="float: left; margin: 6px 15px;">
                        <img src="/img/icon/email_red.png"
                             alt="Email"/>
                        <span style="color: #FE5757; font-size: 13px; font-weight: bold;"
                              data-out="'Email: ' + headerVM.email">
                        </span>
                    </div>

                </div>
                <div class="f-menu-right-media visible-pad visible-med visible-wid">
                    <div class="fb-page"
                         data-href="<?= $social->getValue() ?>"
                         data-width="288"
                         data-hide-cover="false"
                         data-show-facepile="false"
                         data-show-posts="false"></div>
                </div>
            </div>
        </div>
    </div>
<?php } ?>